#!/bin/bash
#
# Run the initdb, then start solr in the foreground
set -e

if [[ "$VERBOSE" = "yes" ]]; then
    set -x
fi

if [ ! -z "$SOLR_HOME" ] && [ -z "$(ls -A $SOLR_HOME)" ]; then
    cp -R /opt/solr/server/solr/* $SOLR_HOME
fi

. /opt/docker-solr/scripts/run-initdb

exec solr -f "$@"
