#!/bin/bash
#
# Run the initdb, then start solr in the foreground
set -e

if [[ "$VERBOSE" = "yes" ]]; then
    set -x
fi

if [ ! -z "$SOLR_DATA_DIR" ]; then
    find "$SOLR_DATA_DIR" -maxdepth 1 -mindepth 1 -type d -exec ln -s {} /opt/solr/server/core/ ';'
fi

. /opt/docker-solr/scripts/run-initdb

exec solr -p 8080 -f "$@"
